This notebook is about training the vanilla CNN on MNIST

In [1]:
require 'torch'
require 'nn'
require 'nnx'
require 'optim'
require 'image'
require 'dataset-mnist' --This is a file which simply donwloads the data TODO: modify it for artificial one
require 'pl'
require 'paths'

We will fix seed for debugging

In [2]:
torch.manualSeed(1234)

We will set the number of threads, this is mostly required for CPU debugging. I have no GPUs on my laptop. We will also set the type to float since we are using SGD during training

In [15]:
torch.setnumthreads(4)
torch.setdefaulttensortype('torch.FloatTensor')
opt = {}
opt.plot = true
opt.batchSize = 10

Here, we define the basic architecture

In [4]:
classes = {'1','2','3','4','5','6','7','8','9','10'}
geometry = {32,32}
model = nn.Sequential()
-- stage 1 : mean suppresion -> filter bank -> squashing -> max pooling
model:add(nn.SpatialConvolutionMM(1, 32, 5, 5)) -- now it is 28x28x32
model:add(nn.Tanh())
model:add(nn.SpatialMaxPooling(3, 3, 3, 3)) -- now it is 8x8x32

-- stage 2 : mean suppresion -> filter bank -> squashing -> max pooling
model:add(nn.SpatialConvolutionMM(32, 64, 5, 5)) -- now it is 4x4x64
model:add(nn.Tanh())
model:add(nn.SpatialMaxPooling(2, 2, 2, 2)) -- now it is 2x2x64
-- stage 3 : standard 2-layer MLP:
model:add(nn.Reshape(64*2*2))
model:add(nn.Linear(64*2*2, 200))
model:add(nn.Tanh())
model:add(nn.Linear(200, #classes))
print(tostring(model))

nn.Sequential {
  [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> output]
  (1): nn.SpatialConvolutionMM(1 -> 32, 5x5)
  (2): nn.Tanh
  (3): nn.SpatialMaxPooling(3,3,3,3)
  (4): nn.SpatialConvolutionMM(32 -> 64, 5x5)
  (5): nn.Tanh
  (6): nn.SpatialMaxPooling(2,2,2,2)
  (7): nn.Reshape(256)
  (8): nn.Linear(256 -> 200)
  (9): nn.Tanh
  (10): nn.Linear(200 -> 10)
}	


Add the loss function at the end

In [5]:
parameters,gradParameters = model:getParameters()
model:add(nn.LogSoftMax())
criterion = nn.ClassNLLCriterion()

We get the dataset

In [6]:
use_full = false
if use_full then
   nbTrainingPatches = 60000
   nbTestingPatches = 10000
else
   nbTrainingPatches = 2000
   nbTestingPatches = 1000
   print('<warning> only using 2000 samples to train quickly (modify use_fil to use 60000 samples)')
end

trainData = mnist.loadTrainSet(nbTrainingPatches, geometry)
trainData:normalizeGlobal(mean, std)

testData = mnist.loadTestSet(nbTestingPatches, geometry)
testData:normalizeGlobal(mean, std)

<warning> only using 2000 samples to train quickly (modify use_fil to use 60000 samples)	


<mnist> loading only 2000 examples	
<mnist> done	


<mnist> loading only 1000 examples	
<mnist> done	


In [7]:
_,t = trainData[1][2]:clone():max(1)
print(t)
t:squeeze()
print(t)

 6
[torch.LongTensor of size 1]

 6
[torch.LongTensor of size 1]



In [9]:
-- this matrix records the current confusion across classes
confusion = optim.ConfusionMatrix(classes)

-- log results to files
trainLogger = optim.Logger(paths.concat("logs", 'train.log'))
testLogger = optim.Logger(paths.concat("logs", 'test.log'))


In [17]:
-- training function
function train(dataset)
   -- epoch tracker
   epoch = epoch or 1

   -- local vars
   local time = sys.clock()

   -- do one epoch
   print('<trainer> on training set:')
   print("<trainer> online epoch # " .. epoch .. ' [batchSize = ' .. 10 .. ']')
   for t = 1,dataset:size(),opt.batchSize do
      -- create mini batch
      local inputs = torch.Tensor(opt.batchSize,1,geometry[1],geometry[2])
      local targets = torch.Tensor(opt.batchSize)
      local k = 1
      for i = t,math.min(t+opt.batchSize-1,dataset:size()) do
         -- load new sample
         local sample = dataset[i]
         local input = sample[1]:clone()
         local _,target = sample[2]:clone():max(1)
         target = target:squeeze()
         inputs[k] = input
         targets[k] = target
         k = k + 1
      end

      -- create closure to evaluate f(X) and df/dX
      local feval = function(x)
         -- just in case:
         collectgarbage()

         -- get new parameters
         if x ~= parameters then
            parameters:copy(x)
         end

         -- reset gradients
         gradParameters:zero()

         -- evaluate function for complete mini batch
         local outputs = model:forward(inputs)
         local f = criterion:forward(outputs, targets)

         -- estimate df/dW
         local df_do = criterion:backward(outputs, targets)
         model:backward(inputs, df_do)

         -- update confusion
         for i = 1,opt.batchSize do
            confusion:add(outputs[i], targets[i])
         end

         -- return f and df/dX
         return f,gradParameters
      end

    
      -- Perform SGD step:
      sgdState = sgdState or {
          learningRate = 0.05,
          momentum = 0,
          learningRateDecay = 5e-7
      }
      optim.sgd(feval, parameters, sgdState)
      
      -- disp progress
      xlua.progress(t, dataset:size())
   end
   
   -- time taken
   time = sys.clock() - time
   time = time / dataset:size()
   print("<trainer> time to learn 1 sample = " .. (time*1000) .. 'ms')

   -- print confusion matrix
   print(confusion)
   trainLogger:add{['% mean class accuracy (train set)'] = confusion.totalValid * 100}
   confusion:zero()

   -- save/log current net
   local filename = paths.concat("logs", 'mnist.net')
   os.execute('mkdir -p ' .. sys.dirname(filename))
   if paths.filep(filename) then
      os.execute('mv ' .. filename .. ' ' .. filename .. '.old')
   end
   print('<trainer> saving network to '..filename)
   -- torch.save(filename, model)

   -- next epoch
   epoch = epoch + 1
end

In [14]:
-- test function
function test(dataset)
   -- local vars
   local time = sys.clock()

   -- test over given dataset
   print('<trainer> on testing Set:')
   for t = 1,dataset:size(),opt.batchSize do
      -- disp progress
      xlua.progress(t, dataset:size())

      -- create mini batch
      local inputs = torch.Tensor(opt.batchSize,1,geometry[1],geometry[2])
      local targets = torch.Tensor(opt.batchSize)
      local k = 1
      for i = t,math.min(t+opt.batchSize-1,dataset:size()) do
         -- load new sample
         local sample = dataset[i]
         local input = sample[1]:clone()
         local _,target = sample[2]:clone():max(1)
         target = target:squeeze()
         inputs[k] = input
         targets[k] = target
         k = k + 1
      end

      -- test samples
      local preds = model:forward(inputs)

      -- confusion:
      for i = 1,opt.batchSize do
         confusion:add(preds[i], targets[i])
      end
   end

   -- timing
   time = sys.clock() - time
   time = time / dataset:size()
   print("<trainer> time to test 1 sample = " .. (time*1000) .. 'ms')

   -- print confusion matrix
   print(confusion)
   testLogger:add{['% mean class accuracy (test set)'] = confusion.totalValid * 100}
   confusion:zero()
end


In [ ]:
-- and train!
--
while true do
   -- train/test
   train(trainData)
   test(testData)

   -- plot errors
   if opt.plot then
      trainLogger:style{['% mean class accuracy (train set)'] = '-'}
      testLogger:style{['% mean class accuracy (test set)'] = '-'}
      trainLogger:plot()
      testLogger:plot()
   end
end


<trainer> on training set:	
<trainer> online epoch # 1 [batchSize = 10]	


Progress: 1691 / 2000	


<trainer> time to learn 1 sample = 3.4450534582138ms	


ConfusionMatrix:
[[     185       0       0       0       0       1       2       1       2       0]   96.859% 	[class: 1]
 [       0     213       1       3       1       0       0       2       0       0]   96.818% 	[class: 2]
 [       1       2     176       5       4       1       0       4       5       0]   88.889% 	[class: 3]
 [       0       0       2     176       0       6       0       3       2       2]   92.147% 	[class: 4]
 [       0       2       1       0     195       0       7       2       0       7]   91.121% 	[class: 5]
 [       0       1       2       3       4     165       3       0       1       1]   91.667% 	[class: 6]
 [       2       1       2       0       0       2     191       0       2       0]   95.500% 	[class: 7]
 [       0       1       6       0       4       0       0     202       0      11]   90.179% 	[class: 8]
 [       0       1       3       1       1       5       2       1     154       4]   89.535% 	[class: 9]
 [       3       0       1   

      1 : 1
      2 : 2
      3 : 3
      4 : 4
      

5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10


  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.921
}


<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


<trainer> time to test 1 sample = 1.626119852066ms	


ConfusionMatrix:
[[      83       0       0       0       0       1       0       0       1       0]   97.647% 	[class: 1]
 [       0     124       0       0       0       0       1       0       1       0]   98.413% 	[class: 2]
 [       2       0     108       0       0       0       3       3       0       0]   93.103% 	[class: 3]
 [       0       0       4      94       0       6       0       1       2       0]   87.850% 	[class: 4]
 [       0       1       0       0      99       0       3       0       0       7]   90.000% 	[class: 5]
 [       0       0       0       3       0      78       4       0       1       1]   89.655% 	[class: 6]
 [       3       0       0       0       1       0      83       0       0       0]   95.402% 	[class: 7]
 [       0       0      10       0       0       0       0      87       0       2]   87.879% 	[class: 8]
 [       0       0       3       3       1       1       0       3      77       1]   86.517% 	[class: 9]
 [       0       0       0   

<trainer> on training set:	
<trainer> online epoch # 2 [batchSize = 10]	


Progress: 201 / 2000	


Progress: 1171 / 2000	


<trainer> time to learn 1 sample = 4.6094545125961ms	


ConfusionMatrix:
[[     188       0       0       0       0       1       1       1       0       0]   98.429% 	[class: 1]
 [       0     214       1       2       1       0       0       1       1       0]   97.273% 	[class: 2]
 [       0       0     191       2       1       1       0       2       1       0]   96.465% 	[class: 3]
 [       0       0       1     182       0       4       0       1       2       1]   95.288% 	[class: 4]
 [       0       2       0       0     202       0       4       1       0       5]   94.393% 	[class: 5]
 [       0       1       1       2       2     172       1       0       0       1]   95.556% 	[class: 6]
 [       2       0       0       0       0       2     195       0       1       0]   97.500% 	[class: 7]
 [       0       1       2       0       3       0       0     212       0       6]   94.643% 	[class: 8]
 [       0       0       3       1       0       1       1       1     163       2]   94.767% 	[class: 9]
 [       3       0       0   

<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


Progress: 321 / 1000	


<trainer> time to test 1 sample = 0.67879509925842ms	
ConfusionMatrix:
[[      83       0       0       0       0       1       1       0       0       0]   97.647% 	[class: 1]
 [       0     124       0       0       0       0       1       0       1       0]   98.413% 	[class: 2]
 [       2       0     108       0       0       0       3       3       0       0]   93.103% 	[class: 3]
 [       0       0       4      99       0       3       0       1       0       0]   92.523% 	[class: 4]
 [       0       1       0       0      99       0       3       0       0       7]   90.000% 	[class: 5]
 [       0       0       0       4       0      77       4       0       2       0]   88.506% 	[class: 6]
 [       3       0       0       0       1       0      83       0       0       0]   95.402% 	[class: 7]
 [       0       0      10       0       0       0       0      86       0       3]   86.869% 	[class: 8]
 [       0       0       3       4       1       0       0       1      79       

<trainer> on training set:	
<trainer> online epoch # 3 [batchSize = 10]	


Progress: 1031 / 2000	


Progress: 1731 / 2000	


<trainer> time to learn 1 sample = 4.801195025444ms	


ConfusionMatrix:
[[     190       0       0       0       0       0       1       0       0       0]   99.476% 	[class: 1]
 [       0     215       1       2       0       0       0       1       1       0]   97.727% 	[class: 2]
 [       1       0     195       0       0       0       0       1       1       0]   98.485% 	[class: 3]
 [       0       0       1     186       0       2       0       1       0       1]   97.382% 	[class: 4]
 [       0       1       0       0     206       0       2       0       0       5]   96.262% 	[class: 5]
 [       0       1       1       1       1     175       1       0       0       0]   97.222% 	[class: 6]
 [       1       0       0       0       0       1     198       0       0       0]   99.000% 	[class: 7]
 [       0       0       1       0       1       0       0     219       0       3]   97.768% 	[class: 8]
 [       0       0       1       2       0       0       0       0     167       2]   97.093% 	[class: 9]
 [       3       0       0   

      2 : 2
      3 : 3
      4 : 4
      5 : 5
      6 : 6
  

    7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.976
}


<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


<trainer> time to test 1 sample = 2.1451001167297ms	


ConfusionMatrix:
[[      83       0       0       0       0       1       1       0       0       0]   97.647% 	[class: 1]
 [       0     124       0       0       0       0       1       0       1       0]   98.413% 	[class: 2]
 [       2       0     111       0       0       0       2       1       0       0]   95.690% 	[class: 3]
 [       0       0       3     100       0       3       0       1       0       0]   93.458% 	[class: 4]
 [       0       1       0       0      98       0       3       0       0       8]   89.091% 	[class: 5]
 [       0       0       0       3       0      79       3       0       2       0]   90.805% 	[class: 6]
 [       3       0       0       0       1       0      83       0       0       0]   95.402% 	[class: 7]
 [       0       0       7       2       0       0       0      87       0       3]   87.879% 	[class: 8]
 [       0       0       3       4       0       0       0       0      82       0]   92.135% 	[class: 9]
 [       0       0       0   

<trainer> on training set:	
<trainer> online epoch # 4 [batchSize = 10]	


Progress: 311 / 2000	


<trainer> time to learn 1 sample = 1.3136239051819ms	
ConfusionMatrix:
[[     190       0       0       0       0       0       1       0       0       0]   99.476% 	[class: 1]
 [       0     218       0       1       0       0       0       1       0       0]   99.091% 	[class: 2]
 [       1       0     195       0       0       0       0       1       1       0]   98.485% 	[class: 3]
 [       0       0       1     187       0       1       0       1       0       1]   97.906% 	[class: 4]
 [       0       1       0       0     211       0       0       0       0       2]   98.598% 	[class: 5]
 [       0       1       1       1       1     176       0       0       0       0]   97.778% 	[class: 6]
 [       1       0       0       0       0       0     199       0       0       0]   99.500% 	[class: 7]
 [       0       0       1       0       0       0       0     221       0       2]   98.661% 	[class: 8]
 [       0       0       1       1       0       0       0       0     169       


    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.986
}


<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


Progress: 921 / 1000	


<trainer> time to test 1 sample = 2.0741438865662ms	


ConfusionMatrix:
[[      84       0       0       0       0       0       0       0       1       0]   98.824% 	[class: 1]
 [       0     124       0       0       0       0       1       0       1       0]   98.413% 	[class: 2]
 [       2       0     112       0       0       0       1       1       0       0]   96.552% 	[class: 3]
 [       0       0       3     101       0       3       0       0       0       0]   94.393% 	[class: 4]
 [       0       0       0       0      97       0       3       0       3       7]   88.182% 	[class: 5]
 [       0       0       1       3       0      80       1       0       2       0]   91.954% 	[class: 6]
 [       3       0       0       0       1       0      83       0       0       0]   95.402% 	[class: 7]
 [       0       0       7       3       0       0       0      85       0       4]   85.859% 	[class: 8]
 [       0       0       3       3       0       0       0       0      83       0]   93.258% 	[class: 9]
 [       0       0       0   

     4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.939
}


<trainer> on training set:	
<trainer> online epoch # 5 [batchSize = 10]	


Progress: 701 / 2000	


Progress: 1611 / 2000	


<trainer> time to learn 1 sample = 4.394602894783ms	


ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     218       1       0       0       0       0       1       0       0]   99.091% 	[class: 2]
 [       0       0     197       0       0       0       0       1       0       0]   99.495% 	[class: 3]
 [       0       0       0     188       0       1       0       1       0       1]   98.429% 	[class: 4]
 [       0       0       0       0     213       0       0       0       0       1]   99.533% 	[class: 5]
 [       0       1       0       0       0     179       0       0       0       0]   99.444% 	[class: 6]
 [       1       0       0       0       0       0     199       0       0       0]   99.500% 	[class: 7]
 [       0       0       0       0       0       0       0     222       0       2]   99.107% 	[class: 8]
 [       0       0       0       0       0       0       0       0     172       0]   100.000% 	[class: 9]
 [       1       0       0 

<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


<trainer> time to test 1 sample = 1.0483829975128ms	


ConfusionMatrix:
[[      85       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     124       0       0       0       0       1       0       1       0]   98.413% 	[class: 2]
 [       2       0     112       0       0       0       1       1       0       0]   96.552% 	[class: 3]
 [       0       0       2     102       0       3       0       0       0       0]   95.327% 	[class: 4]
 [       0       1       0       0      98       0       3       0       0       8]   89.091% 	[class: 5]
 [       0       0       1       2       0      82       1       0       1       0]   94.253% 	[class: 6]
 [       3       0       0       0       1       0      83       0       0       0]   95.402% 	[class: 7]
 [       0       0       6       3       0       0       0      86       0       4]   86.869% 	[class: 8]
 [       0       0       2       3       0       0       0       0      83       1]   93.258% 	[class: 9]
 [       0       0       0  

<trainer> on training set:	
<trainer> online epoch # 6 [batchSize = 10]	


Progress: 721 / 2000	


Progress: 1461 / 2000	


<trainer> time to learn 1 sample = 5.1558765172958ms	


ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     220       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0       0     198       0       0       0       0       0       0       0]   100.000% 	[class: 3]
 [       0       0       1     190       0       0       0       0       0       0]   99.476% 	[class: 4]
 [       0       0       0       0     213       0       0       0       0       1]   99.533% 	[class: 5]
 [       0       0       0       0       0     180       0       0       0       0]   100.000% 	[class: 6]
 [       1       0       0       0       0       0     199       0       0       0]   99.500% 	[class: 7]
 [       0       0       0       0       0       0       0     224       0       0]   100.000% 	[class: 8]
 [       0       0       0       0       0       0       0       0     172       0]   100.000% 	[class: 9]
 [       1       0     

  9 : 9


      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.998
}


<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	


<trainer> on testing Set:	


Progress: 121 / 1000	


<trainer> time to test 1 sample = 1.6379618644714ms	
ConfusionMatrix:
[[      85       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     124       0       0       0       0       1       0       1       0]   98.413% 	[class: 2]
 [       2       0     111       0       0       0       1       2       0       0]   95.690% 	[class: 3]
 [       0       0       2     102       0       3       0       0       0       0]   95.327% 	[class: 4]
 [       0       1       0       0      99       0       2       0       0       8]   90.000% 	[class: 5]
 [       0       0       1       2       0      81       1       0       1       1]   93.103% 	[class: 6]
 [       2       0       0       0       1       0      84       0       0       0]   96.552% 	[class: 7]
 [       0       0       4       2       0       0       0      90       0       3]   90.909% 	[class: 8]
 [       1       0       2       4       1       0       0       0      80       

<trainer> on training set:	
<trainer> online epoch # 7 [batchSize = 10]	


Progress: 1511 / 2000	

<trainer> time to learn 1 sample = 2.9492990970612ms	


ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     220       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0       0     198       0       0       0       0       0       0       0]   100.000% 	[class: 3]
 [       0       0       0     191       0       0       0       0       0       0]   100.000% 	[class: 4]
 [       0       0       0       0     214       0       0       0       0       0]   100.000% 	[class: 5]
 [       0       0       0       0       0     180       0       0       0       0]   100.000% 	[class: 6]
 [       1       0       0       0       0       0     199       0       0       0]   99.500% 	[class: 7]
 [       0       0       0       0       0       0       0     224       0       0]   100.000% 	[class: 8]
 [       0       0       0       0       0       0       0       0     172       0]   100.000% 	[class: 9]
 [       0       0   


  _targ_idx : LongTensor - empty
  averageValid : 0.99950000047684
  classes : 
    {
      1 : 1
      2 : 2
      3 : 3
      4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.9995
}


<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


Progress: 461 / 1000	


<trainer> time to test 1 sample = 3.0399529933929ms	


ConfusionMatrix:
[[      85       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     124       0       0       0       0       1       0       1       0]   98.413% 	[class: 2]
 [       2       0     110       0       0       0       2       2       0       0]   94.828% 	[class: 3]
 [       0       0       2     101       0       4       0       0       0       0]   94.393% 	[class: 4]
 [       0       1       0       0     100       0       2       0       0       7]   90.909% 	[class: 5]
 [       0       0       1       1       0      82       1       0       1       1]   94.253% 	[class: 6]
 [       2       0       0       0       1       0      84       0       0       0]   96.552% 	[class: 7]
 [       0       0       3       1       0       0       0      92       0       3]   92.929% 	[class: 8]
 [       1       0       2       2       2       0       0       0      81       1]   91.011% 	[class: 9]
 [       0       0       0  

 _targ_idx : LongTensor - empty
  averageValid : 0.95115936994553
  classes : 
    {
      1 : 1
      2 : 2
      3 : 3
      4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10


  totalValid : 0.951
}


<trainer> on training set:	
<trainer> online epoch # 8 [batchSize = 10]	


Progress: 1381 / 2000	


<trainer> time to learn 1 sample = 2.2677345275879ms	


ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     220       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0       0     198       0       0       0       0       0       0       0]   100.000% 	[class: 3]
 [       0       0       0     191       0       0       0       0       0       0]   100.000% 	[class: 4]
 [       0       0       0       0     214       0       0       0       0       0]   100.000% 	[class: 5]
 [       0       0       0       0       0     180       0       0       0       0]   100.000% 	[class: 6]
 [       0       0       0       0       0       0     200       0       0       0]   100.000% 	[class: 7]
 [       0       0       0       0       0       0       0     224       0       0]   100.000% 	[class: 8]
 [       0       0       0       0       0       0       0       0     172       0]   100.000% 	[class: 9]
 [       0       0  

     3 : 3
      4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
 

 _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 1
}


<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


Progress: 631 / 1000	


<trainer> time to test 1 sample = 3.0512509346008ms	


ConfusionMatrix:
[[      84       0       0       0       0       1       0       0       0       0]   98.824% 	[class: 1]
 [       0     124       0       0       0       0       1       0       1       0]   98.413% 	[class: 2]
 [       2       0     110       0       0       0       2       2       0       0]   94.828% 	[class: 3]
 [       0       0       2     101       0       4       0       0       0       0]   94.393% 	[class: 4]
 [       0       1       0       0     100       0       2       0       0       7]   90.909% 	[class: 5]
 [       0       0       1       1       0      82       1       0       1       1]   94.253% 	[class: 6]
 [       2       0       0       0       1       0      84       0       0       0]   96.552% 	[class: 7]
 [       0       0       3       1       0       0       0      92       0       3]   92.929% 	[class: 8]
 [       1       0       2       2       2       0       0       0      81       1]   91.011% 	[class: 9]
 [       0       0       0   

 classes : 
    {
      1 : 1
      2 : 2
      3 : 3
      4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.95
}


<trainer> on training set:	
<trainer> online epoch # 9 [batchSize = 10]	


Progress: 551 / 2000	


<trainer> time to learn 1 sample = 3.3587590456009ms	
ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     220       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0       0     198       0       0       0       0       0       0       0]   100.000% 	[class: 3]
 [       0       0       0     191       0       0       0       0       0       0]   100.000% 	[class: 4]
 [       0       0       0       0     214       0       0       0       0       0]   100.000% 	[class: 5]
 [       0       0       0       0       0     180       0       0       0       0]   100.000% 	[class: 6]
 [       0       0       0       0       0       0     200       0       0       0]   100.000% 	[class: 7]
 [       0       0       0       0       0       0       0     224       0       0]   100.000% 	[class: 8]
 [       0       0       0       0       0       0       0       0     17

valids : FloatTensor - size: 10
  mat : LongTensor - size: 10x10
  averageUnionValid : 1
  _targ_idx : LongTensor - empty
  averageValid : 1
  classes : 
    {
      1 : 1
      2 : 2
      3 : 3
      4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 1
}


<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	


<trainer> on testing Set:	


Progress: 61 / 1000	


<trainer> time to test 1 sample = 3.9106070995331ms	


ConfusionMatrix:
[[      84       0       0       0       0       1       0       0       0       0]   98.824% 	[class: 1]
 [       0     125       0       0       0       0       0       0       1       0]   99.206% 	[class: 2]
 [       2       0     110       0       0       0       2       2       0       0]   94.828% 	[class: 3]
 [       0       0       1     102       0       4       0       0       0       0]   95.327% 	[class: 4]
 [       0       1       0       0     101       0       1       0       0       7]   91.818% 	[class: 5]
 [       0       0       1       1       0      82       1       0       1       1]   94.253% 	[class: 6]
 [       2       0       0       0       1       0      84       0       0       0]   96.552% 	[class: 7]
 [       0       0       3       1       0       0       0      92       0       3]   92.929% 	[class: 8]
 [       1       0       2       2       2       0       0       0      81       1]   91.011% 	[class: 9]
 [       0       0       0   

  mat : LongTensor - size: 10x10
  averageUnionValid : 0.90907903313637
  _targ_idx : LongTensor - empty
  averageValid : 0.95262021422386
  classes : 
    {
      1 : 1
      2 : 2
      3 : 3
      4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.953
}


<trainer> on training set:	
<trainer> online epoch # 10 [batchSize = 10]	


Progress: 321 / 2000	


Progress: 1211 / 2000	

Progress: 1711 / 2000	


<trainer> time to learn 1 sample = 6.1305494308472ms	


ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     220       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0       0     198       0       0       0       0       0       0       0]   100.000% 	[class: 3]
 [       0       0       0     191       0       0       0       0       0       0]   100.000% 	[class: 4]
 [       0       0       0       0     214       0       0       0       0       0]   100.000% 	[class: 5]
 [       0       0       0       0       0     180       0       0       0       0]   100.000% 	[class: 6]
 [       0       0       0       0       0       0     200       0       0       0]   100.000% 	[class: 7]
 [       0       0       0       0       0       0       0     224       0       0]   100.000% 	[class: 8]
 [       0       0       0       0       0       0       0       0     172       0]   100.000% 	[class: 9]
 [       0       0  


      4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }


  _prediction : FloatTensor - size: 10
 

 _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty


  unionvalids : FloatTensor - size: 10
  totalValid : 1
}


<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	


<trainer> on testing Set:	


<trainer> time to test 1 sample = 2.3087899684906ms	


ConfusionMatrix:
[[      84       0       0       0       0       1       0       0       0       0]   98.824% 	[class: 1]
 [       0     125       0       0       0       0       0       0       1       0]   99.206% 	[class: 2]
 [       2       0     110       0       0       0       2       2       0       0]   94.828% 	[class: 3]
 [       0       0       1     102       0       4       0       0       0       0]   95.327% 	[class: 4]
 [       0       1       0       0     101       0       1       0       0       7]   91.818% 	[class: 5]
 [       0       0       1       1       0      82       1       0       1       1]   94.253% 	[class: 6]
 [       2       0       0       0       1       0      84       0       0       0]   96.552% 	[class: 7]
 [       0       0       3       1       0       0       0      92       0       3]   92.929% 	[class: 8]
 [       1       0       2       2       2       0       0       0      81       1]   91.011% 	[class: 9]
 [       0       0       0   

   7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.953
}


<trainer> on training set:	
<trainer> online epoch # 11 [batchSize = 10]	


Progress: 111 / 2000	


Progress: 1631 / 2000	


<trainer> time to learn 1 sample = 2.5857709646225ms	


ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     220       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0       0     198       0       0       0       0       0       0       0]   100.000% 	[class: 3]
 [       0       0       0     191       0       0       0       0       0       0]   100.000% 	[class: 4]
 [       0       0       0       0     214       0       0       0       0       0]   100.000% 	[class: 5]
 [       0       0       0       0       0     180       0       0       0       0]   100.000% 	[class: 6]
 [       0       0       0       0       0       0     200       0       0       0]   100.000% 	[class: 7]
 [       0       0       0       0       0       0       0     224       0       0]   100.000% 	[class: 8]
 [       0       0       0       0       0       0       0       0     172       0]   100.000% 	[class: 9]
 [       0       0  

9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 1
}


<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


<trainer> time to test 1 sample = 1.7840881347656ms	


ConfusionMatrix:
[[      84       0       0       0       0       1       0       0       0       0]   98.824% 	[class: 1]
 [       0     125       0       0       0       0       0       0       1       0]   99.206% 	[class: 2]
 [       2       0     109       0       0       0       2       3       0       0]   93.966% 	[class: 3]
 [       0       0       1     102       0       4       0       0       0       0]   95.327% 	[class: 4]
 [       0       1       0       0     101       0       1       0       0       7]   91.818% 	[class: 5]
 [       0       0       1       1       0      82       1       0       1       1]   94.253% 	[class: 6]
 [       2       0       0       0       1       0      84       0       0       0]   96.552% 	[class: 7]
 [       0       0       3       1       0       0       0      92       0       3]   92.929% 	[class: 8]
 [       1       0       2       2       2       0       0       0      81       1]   91.011% 	[class: 9]
 [       0       0       0   


    {
      1 : 1
      2 : 2
      3 : 3
      4 : 4
      5 : 5


      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.952
}


<trainer> on training set:	
<trainer> online epoch # 12 [batchSize = 10]	


Progress: 201 / 2000	


Progress: 1501 / 2000	


<trainer> time to learn 1 sample = 4.1216549873352ms	


ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     220       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0       0     198       0       0       0       0       0       0       0]   100.000% 	[class: 3]
 [       0       0       0     191       0       0       0       0       0       0]   100.000% 	[class: 4]
 [       0       0       0       0     214       0       0       0       0       0]   100.000% 	[class: 5]
 [       0       0       0       0       0     180       0       0       0       0]   100.000% 	[class: 6]
 [       0       0       0       0       0       0     200       0       0       0]   100.000% 	[class: 7]
 [       0       0       0       0       0       0       0     224       0       0]   100.000% 	[class: 8]
 [       0       0       0       0       0       0       0       0     172       0]   100.000% 	[class: 9]
 [       0       0  

<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


Progress: 661 / 1000	


<trainer> time to test 1 sample = 2.972913980484ms	


ConfusionMatrix:
[[      84       0       0       0       0       1       0       0       0       0]   98.824% 	[class: 1]
 [       0     125       0       0       0       0       0       0       1       0]   99.206% 	[class: 2]
 [       2       0     109       0       0       0       2       3       0       0]   93.966% 	[class: 3]
 [       0       0       1     102       0       4       0       0       0       0]   95.327% 	[class: 4]
 [       0       1       0       0     101       0       1       0       0       7]   91.818% 	[class: 5]
 [       0       0       1       1       0      82       1       0       1       1]   94.253% 	[class: 6]
 [       2       0       0       0       1       0      84       0       0       0]   96.552% 	[class: 7]
 [       0       0       2       1       0       0       0      93       0       3]   93.939% 	[class: 8]
 [       1       0       2       2       2       0       0       0      81       1]   91.011% 	[class: 9]
 [       0       0       0   

     9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  

_max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.953
}


<trainer> on training set:	
<trainer> online epoch # 13 [batchSize = 10]	


Progress: 1071 / 2000	


<trainer> time to learn 1 sample = 3.0096116065979ms	


ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     220       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0       0     198       0       0       0       0       0       0       0]   100.000% 	[class: 3]
 [       0       0       0     191       0       0       0       0       0       0]   100.000% 	[class: 4]
 [       0       0       0       0     214       0       0       0       0       0]   100.000% 	[class: 5]
 [       0       0       0       0       0     180       0       0       0       0]   100.000% 	[class: 6]
 [       0       0       0       0       0       0     200       0       0       0]   100.000% 	[class: 7]
 [       0       0       0       0       0       0       0     224       0       0]   100.000% 	[class: 8]
 [       0       0       0       0       0       0       0       0     172       0]   100.000% 	[class: 9]
 [       0       0  

<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


Progress: 911 / 1000	


<trainer> time to test 1 sample = 1.6385409832001ms	


ConfusionMatrix:
[[      84       0       0       0       0       1       0       0       0       0]   98.824% 	[class: 1]
 [       0     125       0       0       0       0       0       0       1       0]   99.206% 	[class: 2]
 [       2       0     109       0       0       0       2       3       0       0]   93.966% 	[class: 3]
 [       0       0       1     102       0       4       0       0       0       0]   95.327% 	[class: 4]
 [       0       1       0       0     101       0       1       0       0       7]   91.818% 	[class: 5]
 [       0       0       1       1       0      82       1       0       1       1]   94.253% 	[class: 6]
 [       2       0       0       0       1       0      84       0       0       0]   96.552% 	[class: 7]
 [       0       0       2       1       0       0       0      93       0       3]   93.939% 	[class: 8]
 [       1       0       2       2       2       0       0       0      81       1]   91.011% 	[class: 9]
 [       0       0       0   

  valids : FloatTensor - size: 10
  mat : LongTensor - size: 10x10
  averageUnionValid : 0.90908758640289
  _targ_idx : LongTensor - empty
  averageValid : 0.95276824831963
  classes : 
    {
      1 : 1
      2 : 2
      3 : 3
      4 : 4


      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  

_pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.953
}


<trainer> on training set:	
<trainer> online epoch # 14 [batchSize = 10]	


Progress: 1011 / 2000	


<trainer> time to learn 1 sample = 3.8534605503082ms	


ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     220       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0       0     198       0       0       0       0       0       0       0]   100.000% 	[class: 3]
 [       0       0       0     191       0       0       0       0       0       0]   100.000% 	[class: 4]
 [       0       0       0       0     214       0       0       0       0       0]   100.000% 	[class: 5]
 [       0       0       0       0       0     180       0       0       0       0]   100.000% 	[class: 6]
 [       0       0       0       0       0       0     200       0       0       0]   100.000% 	[class: 7]
 [       0       0       0       0       0       0       0     224       0       0]   100.000% 	[class: 8]
 [       0       0       0       0       0       0       0       0     172       0]   100.000% 	[class: 9]
 [       0       0  

<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


Progress: 221 / 1000	


<trainer> time to test 1 sample = 1.445494890213ms	


ConfusionMatrix:
[[      84       0       0       0       0       1       0       0       0       0]   98.824% 	[class: 1]
 [       0     126       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       2       0     109       0       0       0       2       3       0       0]   93.966% 	[class: 3]
 [       0       0       1     102       0       4       0       0       0       0]   95.327% 	[class: 4]
 [       0       1       0       0     101       0       1       0       0       7]   91.818% 	[class: 5]
 [       0       0       1       1       0      83       1       0       1       0]   95.402% 	[class: 6]
 [       2       0       0       0       1       0      84       0       0       0]   96.552% 	[class: 7]
 [       0       0       2       1       0       0       0      93       0       3]   93.939% 	[class: 8]
 [       1       0       2       2       2       0       0       0      81       1]   91.011% 	[class: 9]
 [       0       0       0  

      4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.955
}


<trainer> on training set:	
<trainer> online epoch # 15 [batchSize = 10]	


Progress: 1061 / 2000	


<trainer> time to learn 1 sample = 3.3576655387878ms	


ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     220       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0       0     198       0       0       0       0       0       0       0]   100.000% 	[class: 3]
 [       0       0       0     191       0       0       0       0       0       0]   100.000% 	[class: 4]
 [       0       0       0       0     214       0       0       0       0       0]   100.000% 	[class: 5]
 [       0       0       0       0       0     180       0       0       0       0]   100.000% 	[class: 6]
 [       0       0       0       0       0       0     200       0       0       0]   100.000% 	[class: 7]
 [       0       0       0       0       0       0       0     224       0       0]   100.000% 	[class: 8]
 [       0       0       0       0       0       0       0       0     172       0]   100.000% 	[class: 9]
 [       0       0  

  valids : FloatTensor - size: 10
  mat : LongTensor - size: 10x10
  averageUnionValid : 1
  _targ_idx : LongTensor - empty
  averageValid : 1
  classes : 
    {
      1 : 1
      2 : 2
      3 : 3
      4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10


  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 1
}


<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


Progress: 51 / 1000	


<trainer> time to test 1 sample = 1.6223840713501ms	
ConfusionMatrix:
[[      84       0       0       0       0       1       0       0       0       0]   98.824% 	[class: 1]
 [       0     126       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       2       0     109       0       0       0       2       3       0       0]   93.966% 	[class: 3]
 [       0       0       1     102       0       4       0       0       0       0]   95.327% 	[class: 4]
 [       0       1       0       0     101       0       1       0       0       7]   91.818% 	[class: 5]
 [       0       0       1       1       0      83       1       0       1       0]   95.402% 	[class: 6]
 [       2       0       0       0       1       0      84       0       0       0]   96.552% 	[class: 7]
 [       0       0       2       1       0       0       0      93       0       3]   93.939% 	[class: 8]
 [       1       0       2       2       2       0       0       0      81       

{
      1 : 1
      2 : 2
      3 : 3
      4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.955
}


<trainer> on training set:	
<trainer> online epoch # 16 [batchSize = 10]	


Progress: 1061 / 2000	


<trainer> time to learn 1 sample = 3.2020465135574ms	


ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     220       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0       0     198       0       0       0       0       0       0       0]   100.000% 	[class: 3]
 [       0       0       0     191       0       0       0       0       0       0]   100.000% 	[class: 4]
 [       0       0       0       0     214       0       0       0       0       0]   100.000% 	[class: 5]
 [       0       0       0       0       0     180       0       0       0       0]   100.000% 	[class: 6]
 [       0       0       0       0       0       0     200       0       0       0]   100.000% 	[class: 7]
 [       0       0       0       0       0       0       0     224       0       0]   100.000% 	[class: 8]
 [       0       0       0       0       0       0       0       0     172       0]   100.000% 	[class: 9]
 [       0       0  


      2 : 2
      3 : 3
      4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 1
}


<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


Progress: 61 / 1000	


<trainer> time to test 1 sample = 1.7856199741364ms	


ConfusionMatrix:
[[      84       0       0       0       0       1       0       0       0       0]   98.824% 	[class: 1]
 [       0     126       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       2       0     109       0       0       0       2       3       0       0]   93.966% 	[class: 3]
 [       0       0       1     102       0       4       0       0       0       0]   95.327% 	[class: 4]
 [       0       1       0       0     101       0       1       0       0       7]   91.818% 	[class: 5]
 [       0       0       1       1       0      83       1       0       1       0]   95.402% 	[class: 6]
 [       2       0       0       0       1       0      84       0       0       0]   96.552% 	[class: 7]
 [       0       0       2       1       0       0       0      93       0       3]   93.939% 	[class: 8]
 [       1       0       2       2       2       0       0       0      81       1]   91.011% 	[class: 9]
 [       0       0       0  

valids : FloatTensor - size: 10
  mat : LongTensor - size: 10x10
  averageUnionValid : 0.9127775490284
  _targ_idx : LongTensor - empty
  averageValid : 0.95471132993698
  classes : 
    {
      1 : 1
      2 : 2
      3 : 3
      4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.955
}


<trainer> on training set:	
<trainer> online epoch # 17 [batchSize = 10]	


Progress: 791 / 2000	


Progress: 1631 / 2000	


<trainer> time to learn 1 sample = 3.8292169570923ms	


ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     220       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0       0     198       0       0       0       0       0       0       0]   100.000% 	[class: 3]
 [       0       0       0     191       0       0       0       0       0       0]   100.000% 	[class: 4]
 [       0       0       0       0     214       0       0       0       0       0]   100.000% 	[class: 5]
 [       0       0       0       0       0     180       0       0       0       0]   100.000% 	[class: 6]
 [       0       0       0       0       0       0     200       0       0       0]   100.000% 	[class: 7]
 [       0       0       0       0       0       0       0     224       0       0]   100.000% 	[class: 8]
 [       0       0       0       0       0       0       0       0     172       0]   100.000% 	[class: 9]
 [       0       0  

 6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 1
}


<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


<trainer> time to test 1 sample = 1.4619159698486ms	
ConfusionMatrix:
[[      84       0       0       0       0       1       0       0       0       0]   98.824% 	[class: 1]
 [       0     126       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       2       0     109       0       0       0       2       3       0       0]   93.966% 	[class: 3]
 [       0       0       1     102       0       4       0       0       0       0]   95.327% 	[class: 4]
 [       0       1       0       0     101       0       1       0       0       7]   91.818% 	[class: 5]
 [       0       0       1       1       0      83       1       0       1       0]   95.402% 	[class: 6]
 [       2       0       0       0       1       0      84       0       0       0]   96.552% 	[class: 7]
 [       0       0       2       1       0       0       0      93       0       3]   93.939% 	[class: 8]
 [       1       0       2       2       2       0       0       0      81       


{
  valids : FloatTensor - size: 10
  mat : LongTensor - size: 10x10
  averageUnionValid : 0.9127775490284
  _targ_idx : LongTensor - empty
  averageValid : 0.95471132993698
  classes : 
    {
      1 : 1
      2 : 2
      3 : 3
      4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.955
}


<trainer> on training set:	
<trainer> online epoch # 18 [batchSize = 10]	


Progress: 651 / 2000	


<trainer> time to learn 1 sample = 2.563264966011ms	


ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     220       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0       0     198       0       0       0       0       0       0       0]   100.000% 	[class: 3]
 [       0       0       0     191       0       0       0       0       0       0]   100.000% 	[class: 4]
 [       0       0       0       0     214       0       0       0       0       0]   100.000% 	[class: 5]
 [       0       0       0       0       0     180       0       0       0       0]   100.000% 	[class: 6]
 [       0       0       0       0       0       0     200       0       0       0]   100.000% 	[class: 7]
 [       0       0       0       0       0       0       0     224       0       0]   100.000% 	[class: 8]
 [       0       0       0       0       0       0       0       0     172       0]   100.000% 	[class: 9]
 [       0       0  

<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


Progress: 241 / 1000	


<trainer> time to test 1 sample = 1.4454221725464ms	


ConfusionMatrix:
[[      84       0       0       0       0       1       0       0       0       0]   98.824% 	[class: 1]
 [       0     126       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       2       0     109       0       0       0       2       3       0       0]   93.966% 	[class: 3]
 [       0       0       1     102       0       4       0       0       0       0]   95.327% 	[class: 4]
 [       0       1       0       0     101       0       1       0       0       7]   91.818% 	[class: 5]
 [       0       0       1       1       0      83       1       0       1       0]   95.402% 	[class: 6]
 [       2       0       0       0       1       0      84       0       0       0]   96.552% 	[class: 7]
 [       0       0       2       1       0       0       0      93       0       3]   93.939% 	[class: 8]
 [       1       0       2       2       2       0       0       0      81       1]   91.011% 	[class: 9]
 [       0       0       0  

  valids : FloatTensor - size: 10
  mat : LongTensor - size: 10x10
  averageUnionValid : 0.9127775490284
  _targ_idx : LongTensor - empty
  averageValid : 0.95471132993698
  classes : 
    {
      1 : 1
      2 : 2
      3 : 3
      4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.955
}


<trainer> on training set:	
<trainer> online epoch # 19 [batchSize = 10]	


Progress: 1141 / 2000	


<trainer> time to learn 1 sample = 2.6406860351562ms	


ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     220       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0       0     198       0       0       0       0       0       0       0]   100.000% 	[class: 3]
 [       0       0       0     191       0       0       0       0       0       0]   100.000% 	[class: 4]
 [       0       0       0       0     214       0       0       0       0       0]   100.000% 	[class: 5]
 [       0       0       0       0       0     180       0       0       0       0]   100.000% 	[class: 6]
 [       0       0       0       0       0       0     200       0       0       0]   100.000% 	[class: 7]
 [       0       0       0       0       0       0       0     224       0       0]   100.000% 	[class: 8]
 [       0       0       0       0       0       0       0       0     172       0]   100.000% 	[class: 9]
 [       0       0  


      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  

unionvalids : FloatTensor - size: 10
  totalValid : 1
}


<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


Progress: 691 / 1000	


<trainer> time to test 1 sample = 3.377466917038ms	


ConfusionMatrix:
[[      84       0       0       0       0       1       0       0       0       0]   98.824% 	[class: 1]
 [       0     126       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       2       0     109       0       0       0       2       3       0       0]   93.966% 	[class: 3]
 [       0       0       1     102       0       4       0       0       0       0]   95.327% 	[class: 4]
 [       0       1       0       0     101       0       1       0       0       7]   91.818% 	[class: 5]
 [       0       0       1       1       0      83       1       0       1       0]   95.402% 	[class: 6]
 [       2       0       0       0       1       0      84       0       0       0]   96.552% 	[class: 7]
 [       0       0       2       1       0       0       0      93       0       3]   93.939% 	[class: 8]
 [       1       0       2       2       2       0       0       0      81       1]   91.011% 	[class: 9]
 [       0       0       0  

{
      1 : 1
      2 : 2
      3 : 3
      4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
    

  10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1


  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.955
}


<trainer> on training set:	


<trainer> online epoch # 20 [batchSize = 10]	


Progress: 931 / 2000	


<trainer> time to learn 1 sample = 2.709620475769ms	


ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     220       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0       0     198       0       0       0       0       0       0       0]   100.000% 	[class: 3]
 [       0       0       0     191       0       0       0       0       0       0]   100.000% 	[class: 4]
 [       0       0       0       0     214       0       0       0       0       0]   100.000% 	[class: 5]
 [       0       0       0       0       0     180       0       0       0       0]   100.000% 	[class: 6]
 [       0       0       0       0       0       0     200       0       0       0]   100.000% 	[class: 7]
 [       0       0       0       0       0       0       0     224       0       0]   100.000% 	[class: 8]
 [       0       0       0       0       0       0       0       0     172       0]   100.000% 	[class: 9]
 [       0       0  

  unionvalids : FloatTensor - size: 10
  totalValid : 1
}


<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


Progress: 611 / 1000	


<trainer> time to test 1 sample = 2.2745850086212ms	


ConfusionMatrix:
[[      84       0       0       0       0       1       0       0       0       0]   98.824% 	[class: 1]
 [       0     126       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       2       0     109       0       0       0       2       3       0       0]   93.966% 	[class: 3]
 [       0       0       1     102       0       4       0       0       0       0]   95.327% 	[class: 4]
 [       0       1       0       0     101       0       1       0       0       7]   91.818% 	[class: 5]
 [       0       0       1       1       0      83       1       0       1       0]   95.402% 	[class: 6]
 [       2       0       0       0       1       0      84       0       0       0]   96.552% 	[class: 7]
 [       0       0       2       1       0       0       0      93       0       3]   93.939% 	[class: 8]
 [       1       0       2       2       2       0       0       0      81       1]   91.011% 	[class: 9]
 [       0       0       0  

  mat : LongTensor - size: 10x10
  averageUnionValid : 0.9127775490284
  _targ_idx : LongTensor - empty
  averageValid : 0.95471132993698
  classes : 
    {
      1 : 1
      2 : 2
      3 : 3
      4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1


  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.955
}


<trainer> on training set:	
<trainer> online epoch # 21 [batchSize = 10]	


Progress: 801 / 2000	


<trainer> time to learn 1 sample = 3.0695184469223ms	


ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     220       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0       0     198       0       0       0       0       0       0       0]   100.000% 	[class: 3]
 [       0       0       0     191       0       0       0       0       0       0]   100.000% 	[class: 4]
 [       0       0       0       0     214       0       0       0       0       0]   100.000% 	[class: 5]
 [       0       0       0       0       0     180       0       0       0       0]   100.000% 	[class: 6]
 [       0       0       0       0       0       0     200       0       0       0]   100.000% 	[class: 7]
 [       0       0       0       0       0       0       0     224       0       0]   100.000% 	[class: 8]
 [       0       0       0       0       0       0       0       0     172       0]   100.000% 	[class: 9]
 [       0       0  

   10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 1
}


<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


Progress: 651 / 1000	


<trainer> time to test 1 sample = 1.5290100574493ms	


ConfusionMatrix:
[[      84       0       0       0       0       1       0       0       0       0]   98.824% 	[class: 1]
 [       0     126       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       2       0     110       0       0       0       2       2       0       0]   94.828% 	[class: 3]
 [       0       0       1     102       0       4       0       0       0       0]   95.327% 	[class: 4]
 [       0       1       0       0     101       0       1       0       0       7]   91.818% 	[class: 5]
 [       0       0       1       1       0      83       1       0       1       0]   95.402% 	[class: 6]
 [       2       0       0       0       1       0      84       0       0       0]   96.552% 	[class: 7]
 [       0       0       2       1       0       0       0      93       0       3]   93.939% 	[class: 8]
 [       1       0       2       2       2       0       0       0      81       1]   91.011% 	[class: 9]
 [       0       0       0  

5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.956
}


<trainer> on training set:	
<trainer> online epoch # 22 [batchSize = 10]	


Progress: 821 / 2000	


<trainer> time to learn 1 sample = 3.5145169496536ms	


ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     220       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0       0     198       0       0       0       0       0       0       0]   100.000% 	[class: 3]
 [       0       0       0     191       0       0       0       0       0       0]   100.000% 	[class: 4]
 [       0       0       0       0     214       0       0       0       0       0]   100.000% 	[class: 5]
 [       0       0       0       0       0     180       0       0       0       0]   100.000% 	[class: 6]
 [       0       0       0       0       0       0     200       0       0       0]   100.000% 	[class: 7]
 [       0       0       0       0       0       0       0     224       0       0]   100.000% 	[class: 8]
 [       0       0       0       0       0       0       0       0     172       0]   100.000% 	[class: 9]
 [       0       0  

4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 1
}


<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


Progress: 261 / 1000	


<trainer> time to test 1 sample = 1.4964590072632ms	


ConfusionMatrix:
[[      84       0       0       0       0       1       0       0       0       0]   98.824% 	[class: 1]
 [       0     126       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       2       0     110       0       0       0       2       2       0       0]   94.828% 	[class: 3]
 [       0       0       1     102       0       4       0       0       0       0]   95.327% 	[class: 4]
 [       0       1       0       0     101       0       1       0       0       7]   91.818% 	[class: 5]
 [       0       0       1       1       0      83       1       0       1       0]   95.402% 	[class: 6]
 [       2       0       0       0       1       0      84       0       0       0]   96.552% 	[class: 7]
 [       0       0       2       1       0       0       0      93       0       3]   93.939% 	[class: 8]
 [       1       0       2       2       2       0       0       0      81       1]   91.011% 	[class: 9]
 [       0       0       0  

  totalValid : 0.956
}


<trainer> on training set:	
<trainer> online epoch # 23 [batchSize = 10]	


Progress: 951 / 2000	


<trainer> time to learn 1 sample = 2.8883090019226ms	


ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     220       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0       0     198       0       0       0       0       0       0       0]   100.000% 	[class: 3]
 [       0       0       0     191       0       0       0       0       0       0]   100.000% 	[class: 4]
 [       0       0       0       0     214       0       0       0       0       0]   100.000% 	[class: 5]
 [       0       0       0       0       0     180       0       0       0       0]   100.000% 	[class: 6]
 [       0       0       0       0       0       0     200       0       0       0]   100.000% 	[class: 7]
 [       0       0       0       0       0       0       0     224       0       0]   100.000% 	[class: 8]
 [       0       0       0       0       0       0       0       0     172       0]   100.000% 	[class: 9]
 [       0       0  

_prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 1
}


<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


Progress: 881 / 1000	


<trainer> time to test 1 sample = 1.484179019928ms	


ConfusionMatrix:
[[      84       0       0       0       0       1       0       0       0       0]   98.824% 	[class: 1]
 [       0     126       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       2       0     110       0       0       0       2       2       0       0]   94.828% 	[class: 3]
 [       0       0       1     102       0       4       0       0       0       0]   95.327% 	[class: 4]
 [       0       1       0       0     101       0       1       0       0       7]   91.818% 	[class: 5]
 [       0       0       1       1       0      84       1       0       0       0]   96.552% 	[class: 6]
 [       2       0       0       0       1       0      84       0       0       0]   96.552% 	[class: 7]
 [       0       0       2       1       0       0       0      93       0       3]   93.939% 	[class: 8]
 [       1       0       2       2       2       1       0       0      80       1]   89.888% 	[class: 9]
 [       0       0       0  

   7 : 7
      8 : 8
      9 : 9


      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1


  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.956
}


<trainer> on training set:	
<trainer> online epoch # 24 [batchSize = 10]	


Progress: 1241 / 2000	


<trainer> time to learn 1 sample = 2.8893585205078ms	


ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     220       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0       0     198       0       0       0       0       0       0       0]   100.000% 	[class: 3]
 [       0       0       0     191       0       0       0       0       0       0]   100.000% 	[class: 4]
 [       0       0       0       0     214       0       0       0       0       0]   100.000% 	[class: 5]
 [       0       0       0       0       0     180       0       0       0       0]   100.000% 	[class: 6]
 [       0       0       0       0       0       0     200       0       0       0]   100.000% 	[class: 7]
 [       0       0       0       0       0       0       0     224       0       0]   100.000% 	[class: 8]
 [       0       0       0       0       0       0       0       0     172       0]   100.000% 	[class: 9]
 [       0       0  

<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


<trainer> time to test 1 sample = 1.8408710956573ms	


ConfusionMatrix:
[[      84       0       0       0       0       1       0       0       0       0]   98.824% 	[class: 1]
 [       0     126       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       2       0     110       0       0       0       2       2       0       0]   94.828% 	[class: 3]
 [       0       0       1     102       0       4       0       0       0       0]   95.327% 	[class: 4]
 [       0       1       0       0     102       0       1       0       0       6]   92.727% 	[class: 5]
 [       0       0       1       1       0      84       1       0       0       0]   96.552% 	[class: 6]
 [       2       0       0       0       1       0      84       0       0       0]   96.552% 	[class: 7]
 [       0       0       2       1       0       0       0      93       0       3]   93.939% 	[class: 8]
 [       1       0       2       2       2       1       0       0      80       1]   89.888% 	[class: 9]
 [       0       0       0  


      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.957
}


<trainer> on training set:	
<trainer> online epoch # 25 [batchSize = 10]	


Progress: 21 / 2000	


Progress: 861 / 2000	


Progress: 1781 / 2000	


<trainer> time to learn 1 sample = 4.6362439393997ms	
ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     220       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0       0     198       0       0       0       0       0       0       0]   100.000% 	[class: 3]
 [       0       0       0     191       0       0       0       0       0       0]   100.000% 	[class: 4]
 [       0       0       0       0     214       0       0       0       0       0]   100.000% 	[class: 5]
 [       0       0       0       0       0     180       0       0       0       0]   100.000% 	[class: 6]
 [       0       0       0       0       0       0     200       0       0       0]   100.000% 	[class: 7]
 [       0       0       0       0       0       0       0     224       0       0]   100.000% 	[class: 8]
 [       0       0       0       0       0       0       0       0     17

1 : 1
      2 : 2
      3 : 3
      4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 1
}


<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


<trainer> time to test 1 sample = 1.3608510494232ms	


ConfusionMatrix:
[[      84       0       0       0       0       1       0       0       0       0]   98.824% 	[class: 1]
 [       0     126       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       2       0     110       0       0       0       2       2       0       0]   94.828% 	[class: 3]
 [       0       0       1     102       0       4       0       0       0       0]   95.327% 	[class: 4]
 [       0       1       0       0     102       0       1       0       0       6]   92.727% 	[class: 5]
 [       0       0       1       1       0      84       1       0       0       0]   96.552% 	[class: 6]
 [       2       0       0       0       1       0      84       0       0       0]   96.552% 	[class: 7]
 [       0       0       2       1       0       0       0      93       0       3]   93.939% 	[class: 8]
 [       1       0       2       2       2       1       0       0      80       1]   89.888% 	[class: 9]
 [       0       0       0  

<trainer> on training set:	
<trainer> online epoch # 26 [batchSize = 10]	


Progress: 701 / 2000	


Progress: 1751 / 2000	


<trainer> time to learn 1 sample = 3.4451553821564ms	


ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     220       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0       0     198       0       0       0       0       0       0       0]   100.000% 	[class: 3]
 [       0       0       0     191       0       0       0       0       0       0]   100.000% 	[class: 4]
 [       0       0       0       0     214       0       0       0       0       0]   100.000% 	[class: 5]
 [       0       0       0       0       0     180       0       0       0       0]   100.000% 	[class: 6]
 [       0       0       0       0       0       0     200       0       0       0]   100.000% 	[class: 7]
 [       0       0       0       0       0       0       0     224       0       0]   100.000% 	[class: 8]
 [       0       0       0       0       0       0       0       0     172       0]   100.000% 	[class: 9]
 [       0       0  

   2 : 2
      3 : 3
      4 : 4
      5 : 5
      6 : 6


      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 1
}


<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


<trainer> time to test 1 sample = 1.5860719680786ms	


ConfusionMatrix:
[[      84       0       0       0       0       1       0       0       0       0]   98.824% 	[class: 1]
 [       0     126       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       2       0     110       0       0       0       2       2       0       0]   94.828% 	[class: 3]
 [       0       0       1     102       0       4       0       0       0       0]   95.327% 	[class: 4]
 [       0       1       0       0     102       0       1       0       0       6]   92.727% 	[class: 5]
 [       0       0       1       1       0      84       1       0       0       0]   96.552% 	[class: 6]
 [       2       0       0       0       1       0      84       0       0       0]   96.552% 	[class: 7]
 [       0       0       2       1       0       0       0      93       0       3]   93.939% 	[class: 8]
 [       1       0       2       2       2       1       0       0      80       1]   89.888% 	[class: 9]
 [       0       0       0  

<trainer> on training set:	
<trainer> online epoch # 27 [batchSize = 10]	


Progress: 561 / 2000	


Progress: 1531 / 2000	


<trainer> time to learn 1 sample = 4.15567445755ms	

ConfusionMatrix:
[[     191       0       0       0       0       0       0       0       0       0]   100.000% 	[class: 1]
 [       0     220       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       0       0     198       0       0       0       0       0       0       0]   100.000% 	[class: 3]
 [       0       0       0     191       0       0       0       0       0       0]   100.000% 	[class: 4]
 [       0       0       0       0     214       0       0       0       0       0]   100.000% 	[class: 5]
 [       0       0       0       0       0     180       0       0       0       0]   100.000% 	[class: 6]
 [       0       0       0       0       0       0     200       0       0       0]   100.000% 	[class: 7]
 [       0       0       0       0       0       0       0     224       0       0]   100.000% 	[class: 8]
 [       0       0       0       0       0       0       0       0     172       0]   100.000% 	[class: 9]
 [       0       0  


      1 : 1
      2 : 2
      3 : 3
      4 : 4
      5 : 5
      6 : 6
      

7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 1
}


<trainer> saving network to /home/ozan/egocentric-object/src/torch_mnist/logs/mnist.net	
<trainer> on testing Set:	


<trainer> time to test 1 sample = 1.8113820552826ms	


ConfusionMatrix:
[[      84       0       0       0       0       1       0       0       0       0]   98.824% 	[class: 1]
 [       0     126       0       0       0       0       0       0       0       0]   100.000% 	[class: 2]
 [       2       0     110       0       0       0       2       2       0       0]   94.828% 	[class: 3]
 [       0       0       1     102       0       4       0       0       0       0]   95.327% 	[class: 4]
 [       0       1       0       0     102       0       1       0       0       6]   92.727% 	[class: 5]
 [       0       0       1       1       0      84       1       0       0       0]   96.552% 	[class: 6]
 [       2       0       0       0       1       0      84       0       0       0]   96.552% 	[class: 7]
 [       0       0       2       1       0       0       0      93       0       3]   93.939% 	[class: 8]
 [       1       0       2       2       2       1       0       0      80       1]   89.888% 	[class: 9]
 [       0       0       0  

<trainer> on training set:	
<trainer> online epoch # 28 [batchSize = 10]	


Progress: 111 / 2000	


Progress: 631 / 2000	
